set_perm_recursive "$MODPATH" 0 0 0755 0644

ui_print " "
ui_print "注意："
ui_print "- 此模块安装的游戏均为大陆官服版本"
ui_print "- 模块运行日志在 模块安装路径的 run.log 文件下（一般为 /data/adb/mihoyo_module/run.log）"
ui_print "- 安装包会存放在 /data/local/tmp，安装完成后自动删除"
ui_print "- 未对数据流量连接进行特殊处理，请确保您的流量套餐足够下载游戏"
ui_print " "
ui_print "- 原神，启动！"
ui_print "- 崩坏3，启动！"
ui_print "- 崩坏：星穹铁道，启动！"
ui_print "- 崩坏学院2，启动！"
ui_print "- 未定事件簿，启动！"
ui_print "- 米游社，启动！"
ui_print " "
